name: JayTAKRepairPlugin
version: '${project.version}'
main: io.jaytak.jaytakrepairplugin.JayTAKRepairPlugin
api-version: '1.20'
commands:
  jaytakrepair:
    description: Repair command
    aliases:
      - jrepair
      - jrep
      - jr
    usage: /jaytakrepair /jrepair /jrep /jr